### ISSUE TITLE
Can't run other commands than time and wheater

### ISSUE THREAD

**Issue by Sefohui** [aryxs3m/mcdashboard#1]
Hi! I just grabbed your dashboard and at start it looked awesome! The only thing I'm having problems with is that the only thing that seems to work is the weather and time commands. Not the others. I have looked into it and saw that the weather buttons in ´dash_rcon.php´ have a class called: ´btn-rcon-easy´ which no other button have. I don't see anything else connecting the button to a script. Soo I tested to add ´btn-rcon-say´ to the say-button and added this to the js file:
`$(document).ready(function(){

    $(".btn-rcon-easy").click(function(){

        var command = $(this).data("command");
        sendRcon(command, $(this));

    });

    $(".btn-rcon-say").click(function(){

        var command = document.getElementById('say_box').value;
        sendRcon(command, $(this));

    });

});`

That didn't work though. If I return to the ´btn-rcon-easy´ class on the button and add data-command="say test" it works. But since it should be able to change to whatever it says in the input that doesn't really cut it.

I know this project is 2 years old now but if you have any time over it would be soo great if you could look into it since this looks to be the best solution for my friend's server.

Thanks! :D

**Comment by aryxs3m** [comment]
Hi!

I know i'm very late, but just fixed the RCON page, every button and feature works now.

I will not update this project anytime soon, because i started a new, better and nicer Minecraft user/admin web dashboard: [https://github.com/aryxs3m/minecraft_portal](https://github.com/aryxs3m/minecraft_portal)
